global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel-collector-pipeline-metrics
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: otel-collector-self-metrics
    static_configs:
      - targets: ["otel-collector:8888"]
